### ISSUE TITLE
[Request] Rework NitroHax to Use The Usrcheat.dat Database

### ISSUE THREAD

**Issue by DeadSkullzJr** [chishm/nitrohax#7]
Hello, it has been a long time since I have used NitroHax, however now that TWiLightMenu++ is around, it got me thinking about how it handles cheats. TWiLightMenu++ uses the usrcheat.dat database for cheats, and since there isn't a limitation with it, it would be a superb choice to change to for NitroHax. NitroHax and TWiLightMenu both use the same method to grab cheats really, both require their respective databases to be on the SD card of the 3DS (and now the DSi), however NitroHax is stuck using the cheats.xml format, which is a very limited format to use. The Action Replay DS devices were stuck using them, sadly you couldn't have/hold a bunch of cheats in the devices, NitroHax feels the same way, the hard limit is 2.5MB for it. So I was wondering if you could rework NitroHax to utilize the usrcheat.dat database like TWiLightMenu does, that way people aren't limited to a certain amount of codes, and it would give a better option to people wanting to use real physical game carts.

**Comment by chishm** [comment]
Hi,

Thank you for bringing TWiLightMenu++ to my attention. Although it would be great to remove the size limit, unfortunately it's not possible for (original DS) NitroHax. The limit exists because the entire database has to be loaded into RAM before the SD card is removed and the game card is inserted. The XML parsing code uses not much RAM, but the parsed cheat database has to fit within the 4MiB (minus NitroHax code and other data) available on the NDS. So switching to the usrcheat.dat format would not help in this case.
